#! /bin/dash

XMODMAP_CONF="$HOME/.xmodmaprc"

NATURAL_KEYCODE=65
ARTIFICIAL_KEYCODE=255

restore_map() {
    setxkbmap -layout us
    [ -f "$XMODMAP_CONF" ] && xmodmap "$XMODMAP_CONF"
    exit
}

trap restore_map INT

xmodmap - <<- END
    keycode $NATURAL_KEYCODE = Control_L
    keycode $ARTIFICIAL_KEYCODE = space
    add control = Control_L
END

./keydouble $NATURAL_KEYCODE $ARTIFICIAL_KEYCODE

restore_map
