#! /bin/dash

XMODMAP_CONF="$HOME/.xmodmaprc"

NATURAL_KEYCODE=65
ARTIFICIAL_KEYCODE=255

restore_map() {
    lyt=$(setxkbmap -query | grep -i '^layout:' | awk '{print $2}')
    if [ -n "$lyt" ] ; then
        setxkbmap -layout "$lyt"
    else
        printf "couldn't guess the current keyboard layout" >& 2
    fi
    [ -f "$XMODMAP_CONF" ] && xmodmap "$XMODMAP_CONF"
    exit
}

trap restore_map INT

xmodmap - <<- END
    keycode $NATURAL_KEYCODE = Control_L
    keycode $ARTIFICIAL_KEYCODE = space
    add control = Control_L
END

./keydouble $NATURAL_KEYCODE $ARTIFICIAL_KEYCODE

restore_map
